# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.9)
{
  # A helpful description of your flake
  description = "My NixOS Configuration as a Flake";

  # Flake inputs
  inputs = {
    fh.url = "https://flakehub.com/f/DeterminateSystems/fh/0.1.9.tar.gz";
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*.tar.gz";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1.*.tar.gz";
  };

  # Flake outputs that other flakes can use
  outputs = { self, flake-schemas, nixpkgs, ... } @ inputs:
    let
      # Helpers for producing system-specific outputs
      supportedSystems = [ "x86_64-linux" "aarch64-linux" "aarch64-darwin" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs {
          inherit system;
          overlays = [ inputs.fh.overlays.default ];
        };
      });
    in
    {
      # Schemas tell Nix about the structure of your flake's outputs
      schemas = flake-schemas.schemas;

      # Development environments
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          # Pinned packages available in the environment
          packages = with pkgs; [
            nixpkgs-fmt
            nil
            fh
          ];
        };
      });

      nixosConfigurations = {
        workvm = nixpkgs.lib.nixosSystem {
          system = "aarh64-linux";
          modules = [
            ./hosts/workvm
          ];
        };
        workvm-darwin = nixpkgs.lib.nixosSystem {
          system = "aarh64-linux";
          modules = [
            ./hosts/workvm
            { virtualisation.host.pkgs = nixpkgs.legacyPackages.aarch64-darwin; }
          ];
        };
      };

      packages.aarch64-darwin.workvm = self.nixosConfigurations.workvm.config.system.build.vm;
      packages.aarch64-darwin.workvm-darwin = self.nixosConfigurations.workvm-darwin.config.system.build.vm;
    };
}
